---
- name: Install and configure Nginx on Ubuntu and CentOS
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx on Ubuntu
      shell: java -version
      register: get_jdk
      ignore_errors: yes      

    - name: Install Nginx on Ubuntu
      file: dest={{ item }} state=directory
      with_items:
        - "{{ common_bin_software_dest_dir }}"
        - "{{ jdk_base_path }}"
    - name: 2-上传软件
      unarchive: src={{ item }} dest={{ common_bin_software_dest_dir }}
      with_fileglob:
        - "{{ common_bin_software_src_dir }}/jdk*.tar.gz"
    - name: 3-安装jdk
      shell: cd {{ common_bin_software_dest_dir }}/jdk1* && yes | mv * {{ jdk_base_path }}/
      ignore_errors: yes

    - name: 4-配置环境变量
      template: src={{ common_bin_software_dest_dir }}/java.sh.j2 dest={{ jdk_source_file }}

    - name: 验证部署结果
      shell: source /etc/profile && java -version
      register: get_jdk

    - name: 输出部署结果
      debug:
        msg: jdk部署成功！
      when: get_jdk.stdout.find('1.8.0_181') != ""        
