---
- hosts: all
  tasks:
     - name: "liu-test"
       shell: echo "test" `date` by `hostname` >> /tmp/hello.log
     - name: 1-判断jdk是否存在
       shell: java -version
       register: get_jdk
       ignore_errors: yes
     - name: 1-创建软件目录
	file: dest={{ item }} state=directory
	with_items:
	  - "{{ jdk_base_path }}"

