---
- hosts: all
  tasks:
	- name: 1-判断jdk是否存在
	  shell: java -version
	  register: get_jdk
	  ignore_errors: yes
	
	- name: 2-如果存在jdk则删除
	  shell: cd /opt && rm -rf jdk && cd /etc/profile.d && rm -rf java.sh
	  when: get_jdk.stdout.find("version") != ""
	
	- name: 1-创建软件目录
	  file: dest={{ item }} state=directory
	  with_items:
	    - "{{ common_bin_software_dest_dir }}"
	    - "{{ jdk_base_path }}"
	
	- name: 2-上传软件
	  unarchive: src={{ item }} dest={{ common_bin_software_dest_dir }}
	  with_fileglob:
	    - "{{ common_bin_software_src_dir }}/jdk*.tar.gz"
	
	- name: 3-安装jdk
	  shell: cd {{ common_bin_software_dest_dir }}/jdk1* && yes | mv * {{ jdk_base_path }}/
	  ignore_errors: yes
	
	- name: 4-配置环境变量
	  template: src=java.sh.j2 dest={{ jdk_source_file }}
	
	- name: 验证部署结果
	  shell: source /etc/profile && java -version
	  register: get_jdk
	
	- name: 输出部署结果
	  debug:
	    msg: jdk部署成功！
	  when: get_jdk.stdout.find('1.8.0_181') != ""
